<a href="https://colab.research.google.com/github/Bobbyorr007/BASIC-OPERATIONS-PERFORMED-ON-TENSORS/blob/main/BASIC_OPERATIONS_PERFORMED_ON_TENSORS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORTS**

In [1]:
import numpy as np
import tensorflow as tf

**EXERCISE ON BASIC TENSORS**

I created a single dimensional numpy array of size 50, holding values from 0 to 49. 

In [3]:
# Create a 1d uint8 NumPy array comprising of the first 50 natural numbers
x = np.arange(0,50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

I Changed my numpy array into a tensor

In [4]:
# Convert NumPy array into a tensor using the 'tf.constant'
x = tf.constant(x)
x

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])>

I squared(element-wise) all the values in my tensor x.

In [5]:
# Square the input tensor x
x = tf.square(x)
x

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401])>

One feature of tensors is that it can be reshaped. while reshaping make sure to use dimensions that will include all values of your Tensor.


In [7]:
# Reshape Tensor into (5 x 10) matrics...
x = tf.reshape(x, (5,10))
x

<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401]])>

Just like reshaping Tensor, we can also change the data type of Tensors. I will change the data type of my tensor(x) from an int to float.

In [9]:
# cast tensor x into a float32 dtype
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.000e+00, 1.000e+00, 4.000e+00, 9.000e+00, 1.600e+01, 2.500e+01,
        3.600e+01, 4.900e+01, 6.400e+01, 8.100e+01],
       [1.000e+02, 1.210e+02, 1.440e+02, 1.690e+02, 1.960e+02, 2.250e+02,
        2.560e+02, 2.890e+02, 3.240e+02, 3.610e+02],
       [4.000e+02, 4.410e+02, 4.840e+02, 5.290e+02, 5.760e+02, 6.250e+02,
        6.760e+02, 7.290e+02, 7.840e+02, 8.410e+02],
       [9.000e+02, 9.610e+02, 1.024e+03, 1.089e+03, 1.156e+03, 1.225e+03,
        1.296e+03, 1.369e+03, 1.444e+03, 1.521e+03],
       [1.600e+03, 1.681e+03, 1.764e+03, 1.849e+03, 1.936e+03, 2.025e+03,
        2.116e+03, 2.209e+03, 2.304e+03, 2.401e+03]], dtype=float32)>

I created a single value Tensor(float32) in other to show the power of broadcasting. 

In [10]:
# I created a single value tensor of dtype float32 to show thw power of broadcasting in the following cell.
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

I mutiplied the tensor x and y together and experienced the power of broadcasting. The single value tensor (y), multiplied each value/element of the tensor x.

In [12]:
# Multiply tensor x by y. tensor y is multilied to each element of tensor x.
result = tf.multiply(x,y)
result

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.000e+00, 2.000e+00, 8.000e+00, 1.800e+01, 3.200e+01, 5.000e+01,
        7.200e+01, 9.800e+01, 1.280e+02, 1.620e+02],
       [2.000e+02, 2.420e+02, 2.880e+02, 3.380e+02, 3.920e+02, 4.500e+02,
        5.120e+02, 5.780e+02, 6.480e+02, 7.220e+02],
       [8.000e+02, 8.820e+02, 9.680e+02, 1.058e+03, 1.152e+03, 1.250e+03,
        1.352e+03, 1.458e+03, 1.568e+03, 1.682e+03],
       [1.800e+03, 1.922e+03, 2.048e+03, 2.178e+03, 2.312e+03, 2.450e+03,
        2.592e+03, 2.738e+03, 2.888e+03, 3.042e+03],
       [3.200e+03, 3.362e+03, 3.528e+03, 3.698e+03, 3.872e+03, 4.050e+03,
        4.232e+03, 4.418e+03, 4.608e+03, 4.802e+03]], dtype=float32)>

I reinitiaized Tensor y to having more values.

In [15]:
# Reinitialize y to having more values
y = tf.constant([1,2,3,4,5,6,7,8,9,0], dtype=tf.float32)
y

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9., 0.], dtype=float32)>

I added both tensors together and noticed the addition was done in rows.
The tensor 'y' summed up with the first row of tensor 'x' then moved on to the next row, and the next and so on.

In [18]:
# Add tensor x and y together, and notice the summation in rows.
result = x + y
result 

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.000e+00, 3.000e+00, 7.000e+00, 1.300e+01, 2.100e+01, 3.100e+01,
        4.300e+01, 5.700e+01, 7.300e+01, 8.100e+01],
       [1.010e+02, 1.230e+02, 1.470e+02, 1.730e+02, 2.010e+02, 2.310e+02,
        2.630e+02, 2.970e+02, 3.330e+02, 3.610e+02],
       [4.010e+02, 4.430e+02, 4.870e+02, 5.330e+02, 5.810e+02, 6.310e+02,
        6.830e+02, 7.370e+02, 7.930e+02, 8.410e+02],
       [9.010e+02, 9.630e+02, 1.027e+03, 1.093e+03, 1.161e+03, 1.231e+03,
        1.303e+03, 1.377e+03, 1.453e+03, 1.521e+03],
       [1.601e+03, 1.683e+03, 1.767e+03, 1.853e+03, 1.941e+03, 2.031e+03,
        2.123e+03, 2.217e+03, 2.313e+03, 2.401e+03]], dtype=float32)>

When usinf tf.constant, we can pass in a 1D array and using the shape parameter to change into a multi-dimensional array.

In [21]:
# creating a 1D array with tf.constant and using the shape parameter to change into a 2D array.
x = tf.constant([1234], tf.float32, shape=(2,2))
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1234., 1234.],
       [1234., 1234.]], dtype=float32)>

This isnt the case with a tf.Variable created Tensor


In [22]:
# creating a 1D array with tf.Variable and using the shape parameter to change into a multi-dimension. NOTICE THE ValueError THATS POPS UP WHEN THE CODE BLOCK IS RAN
x = tf.Variable([1,2,3,4], tf.float32, shape=(2,2))

ValueError: ignored